version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=your_secure_password

  ray-head:
    image: rayproject/ray
    command: --head --port=6379 --redis-password=your_secure_password
    environment:
      - RAY_REDIS_PASSWORD=your_secure_password

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=your_secure_password
      - RAY_ADDRESS=ray-head:6379
    depends_on:
      - redis
      - ray-head

  hardware-agent:
    build: ./hardware-agent
    environment:
      - BACKEND_URL=http://backend:8000/update-hardware-metrics
    depends_on:
      - backend

volumes:
  redis_data: